version: "3.8"
services:
  redis:
    image: redis:7
    restart: unless-stopped

  coturn:
    image: instrumentisto/coturn:4.5
    restart: unless-stopped
    ports:
      - "3478:3478"     # TURN/TCP
      - "3478:3478/udp" # TURN/UDP
    environment:
      - REALM=77.246.103.197
      - LISTENING_IP=0.0.0.0
      - EXTERNAL_IP=77.246.103.197
      - LT-SECRET=super_long_secure_secret_here
    # In production, mount /etc/turnserver.conf for hardened config

  livekit:
    image: livekit/livekit-server:latest
    depends_on:
      - redis
      - coturn
    environment:
      - LIVEKIT_REDIS_URL=redis://redis:6379/0
      - LIVEKIT_KEYS=${LIVEKIT_KEYS}
      - LIVEKIT_RTC_UDP_PORT=50000
      - LIVEKIT_RTC_UDP_PORT_RANGE=50000-51000
      - LIVEKIT_ICE_SERVERS=[{"urls":["stun:stun.l.google.com:19302"],"urls":["turn:77.246.103.197:3478"],"username":"%username%","credential":"%password%"}]
    ports:
      - "7880:7880"       # REST/admin
      - "7881:7881"       # Ingress (optional)
      - "7882:7882"       # Metrics/admin UI (if enabled)
    restart: unless-stopped

  token-server:
    build: ./token-server
    depends_on:
      - livekit
    environment:
      - LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
      - LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
      - LIVEKIT_URL=https://77.246.103.197
    expose:
      - "8000"
    restart: unless-stopped

  caddy:
    image: caddy:2
    depends_on:
      - livekit
      - token-server
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - /etc/caddy/certs:/etc/caddy/certs:ro
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config: